import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount } from "wagmi";
import { useReadContract, useWriteContract } from "wagmi";
import contract from "../contract.json";
import { FormEvent, useState } from "react";

const Home: NextPage = () => {
    const account = useAccount();
    const [texContract, setTextContract] = useState<string | null>(null);
    const { writeContract } = useWriteContract();
    const { refetch: callGetText } = useReadContract({
        abi: contract.abi,
        address: contract.address as `0x${string}`,
        functionName: "getText",
    });

    const myData = async () => {
        const text = await callGetText();
        console.log(text.data);
        if (text.data && typeof text.data == "string")
            setTextContract(text.data);
    };
    const updateData = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        const newValue = event.target[0]?.value;
        console.log({ newValue });
        if (newValue)
            writeContract({
                abi: contract.abi,
                address: contract.address as `0x${string}`,
                functionName: "setTextPublic",
                args: [newValue],
                // If value is not necessary you have to omit that attribute
                // If you send it, It won't work.
                value: BigInt(2),
            });
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>RainbowKit App</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>

            <main className={styles.main}>
                <ConnectButton />

                <h1 className={styles.title}>
                    Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a>{" "}
                    + <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{" "}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>
                <div>{account ? account.address : ""}</div>
                <button onClick={() => myData()}>
                    Obtener valor del Texto
                </button>
                <div>{texContract ? texContract : ""}</div>
                <form onSubmit={updateData}>
                    <span>Digita el nuevo texto: </span>
                    <br />
                    <input type="text" name="newText" />
                    <br />
                    <button type="submit">Actualizar texto</button>
                </form>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://rainbow.me"
                    rel="noopener noreferrer"
                    target="_blank"
                >
                    Made with ❤️ by your frens at 🌈
                </a>
            </footer>
        </div>
    );
};

export default Home;
